SELECT * FROM EMPLOYEES;
-- 사번, 이름, 성, 상급자 사번 조회
SELECT E1.EMPLOYEE_ID, E1.FIRST_NAME, E1.LAST_NAME, E1.MANAGER_ID, E1.SALARY -- 본인
, E2.EMPLOYEE_ID, E2.FIRST_NAME, E2.LAST_NAME, E2.MANAGER_ID, E2.SALARY -- 상사
, E3.EMPLOYEE_ID, E3.FIRST_NAME, E3.LAST_NAME, E3.MANAGER_ID, E3.SALARY -- 상사의 상사
FROM EMPLOYEES E1, EMPLOYEES E2, EMPLOYEES E3
WHERE E1.MANAGER_ID = E2.EMPLOYEE_ID(+)
AND E2.MANAGER_ID = E3.EMPLOYEE_ID(+)
ORDER BY 1;

SELECT E1.EMPLOYEE_ID ID, E1.FIRST_NAME FN, E1.LAST_NAME LN, E1.MANAGER_ID MID, E1.SALARY S -- 본인
, E2.EMPLOYEE_ID ID2, E2.FIRST_NAME FN2, E2.LAST_NAME LN2, E2.MANAGER_ID MID2, E2.SALARY S2 -- 상사
, E3.EMPLOYEE_ID ID3, E3.FIRST_NAME FN3, E3.LAST_NAME LN3, E3.MANAGER_ID MID3, E3.SALARY S3 -- 상사의 상사
FROM EMPLOYEES E1
LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
LEFT JOIN EMPLOYEES E3 ON E2.MANAGER_ID = E3.EMPLOYEE_ID
ORDER BY 1;