SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE ROWNUM <= 20 AND ROWNUM >10;

-- SUB QUERTY를 활용한 페이지

-- 2페이지 보기 10개씩
SELECT RN, ID FN, LN
FROM (
    SELECT ROWNUM RN, EMPLOYEE_ID ID, FIRST_NAME FN, LAST_NAME LN
    FROM EMPLOYEES
    WHERE ROWNUM <= 2 * 10
)
WHERE RN > (2 - 1) * 10;
    