-- 테이블
CREATE TABLE TBL_BOARD (
    BNO NUMBER,
    TITLE VARCHAR2(300),
    CONTENT CLOB,
    HITCOUNT NUMBER DEFAULT 0,
    REGDATE DATE DEFAULT SYSDATE,
    WRITER VARCHAR2(100),
    CATEGORY NUMBER DEFAULT 1
);

DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER (
    ID VARCHAR2(100),
    PW VARCHAR2(100),
    NAME VARCHAR2(100),
    SI VARCHAR2(100),
    SGG VARCHAR2(100),
    EMD VARCHAR2(100),
    ROADADDR VARCHAR2(500),
    ADDRDETAIL VARCHAR2(20),
    ZIPNO VARCHAR2(10),
    ROADFULLADDR VARCHAR2(500),
    JIBUNADDR VARCHAR2(500),
    EMAIL VARCHAR2(200),
    AUTH CHAR DEFAULT 1,
    AUTH_TOKEN VARCHAR2(100)
);

DROP TABLE TBL_REPLY;
CREATE TABLE TBL_REPLY (
    RNO NUMBER,
    CONTENT VARCHAR2(4000),
    REGDATE DATE DEFAULT SYSDATE,
    BNO NUMBER,
    WRITER VARCHAR(100)
);

DROP TABLE TBL_ATTACH;
CREATE TABLE TBL_ATTACH (
    UUID VARCHAR2(50),
    ORIGIN VARCHAR2(500),
    PATH CHAR(10),
    IMAGE CHAR DEFAULT '0',
    ORD NUMBER DEFAULT 1,
    BNO NUMBER
);

-- 시퀀스
CREATE SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_REPLY;

-- 프로시저
CREATE OR REPLACE PROCEDURE PROC_INSERT_MEMBER(
    V_ID TBL_MEMBER.ID%TYPE,
    V_PW TBL_MEMBER.PW%TYPE,
    V_NAME TBL_MEMBER.NAME%TYPE,
    V_SI TBL_MEMBER.SI%TYPE,
    V_SGG TBL_MEMBER.SGG%TYPE,
    V_EMD TBL_MEMBER.EMD%TYPE,
    V_ROADADDR TBL_MEMBER.ROADADDR%TYPE,
    V_ADDRDETAIL TBL_MEMBER.ADDRDETAIL%TYPE,
    V_ZIPNO TBL_MEMBER.ZIPNO%TYPE,
    V_ROADFULLADDR TBL_MEMBER.ROADFULLADDR%TYPE,
    V_JIBUNADDR TBL_MEMBER.JIBUNADDR%TYPE,
    V_EMAIL TBL_MEMBER.EMAIL%TYPE,
    V_SPEAK TBL_MEMBER.SPEAK%TYPE
) IS
BEGIN
    INSERT INTO TBL_MEMBER (ID, PW, NAME, SI, SGG, EMD, ROADADDR, ADDRDETAIL, ZIPNO, ROADFULLADDR, JIBUNADDR, EMAIL, SPEAK)
    VALUES (V_ID, V_PW, V_NAME, V_SI, V_SGG, V_EMD, V_ROADADDR, V_ADDRDETAIL, V_ZIPNO, V_ROADFULLADDR, V_JIBUNADDR, V_EMAIL, V_SPEAK);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE QUIT_PROC (P_ID TBL_MEMBER.ID%TYPE) IS
BEGIN
    UPDATE TBL_BOARD SET
    WRITER = NULL
    WHERE WRITER = P_ID;

    UPDATE TBL_REPLY SET
    WRITER = NULL
    WHERE WRITER = P_ID;
    
    DELETE TBL_MEMBER
    WHERE ID = P_ID;
    
    COMMIT;
END;
/

-- TEST
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_ATTACH;

SELECT B.*
FROM (
    SELECT ID, NAME, ROWNUM RN
    FROM TBL_MEMBER
    WHERE ROWNUM <= 10
) B
WHERE RN > 0;

-- DATA
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('john', 1234, '존', '잘 때도 조심');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('horang', 1234, '호랭이', '이쪽에는 호랑이, 저쪽에는 타이거');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('ham', 1234, '햄까스', '남의 떡이 더 맛있다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('michel', 1234, '미첼', '중요한 건 타이밍');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('tank', 1234, '탱크', '회색 다리는 회색 마음보다 낫다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('apple', 1234, '애플', '사람들은 닮기 마련');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('bing', 1234, '빙수', '빙수하면 팥빙수');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('king', 1234, '킹', '백수의 왕');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('tako', 1234, '탁호', '1개는 덤');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('sion', 1234, '시온', '용서란 짓밟힌 제비꽃이 발꿈치에 남긴 향기다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('mong', 1234, '원승', '보지도, 듣지도, 말하지도 말라');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('mari', 1234, '마리', '피는 못 속인다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('dream', 1234, '드리미', '개구리 없는 호수 지저분한 호수');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('cham', 1234, '참돌이', '인생 한 방');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('jorz', 1234, '조르쥐', '집에 쥐가 있으면 나라엔 도둑이 있다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('goni', 1234, '곤잘레스', '10마리의 하마는 하나의 구멍에 들어가지 않는다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('peter', 1234, '피터', '사슴 일은 아무도 모른다');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('jack', 1234, '잭슨', '셀프 브랜딩');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('mami', 1234, '마미', '엄마는 아이 생각, 아이는 놀 생각');
INSERT INTO TBL_MEMBER(ID, PW, NAME, SPEAK) VALUES('dragon', 1234, '용남이', '등용문');