SELECT
    (SELECT COUNT(*) FROM TBL_REPLY R WHERE R.BNO = B.BNO) REPLYCNT,
    B.*
FROM TBL_BOARD B
ORDER BY 2 DESC;

INSERT INTO TBL_REPLY (RNO, CONTENT, BNO, WRITER)
VALUES (SEQ_REPLY.NEXTVAL, 'test 내용이다', 309, 'javaman');