SELECT * FROM STUDENT;

-- 학생들의 인원수, 평균키, 평균 몸무게
SELECT DEPTNO, COUNT(*), AVG(HEIGHT), AVG(WEIGHT) FROM STUDENT GROUP BY DEPTNO;

-- 학생의 키 순서 역순 정렬
SELECT * FROM STUDENT ORDER BY HEIGHT DESC;

SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;
SELECT * FROM SALGRADE;

SELECT 'HELLO WORLD' FROM DUAL;

-- 학생의 학번, 이름, 학과이름을 조회
SELECT STUDNO, NAME, DNAME
FROM STUDENT
NATURAL JOIN DEPARTMENT;

SELECT STUDNO, NAME, DNAME
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO = D.DEPTNO;

-- 한줄 주석
/* 범위 주석 */

SELECT SYSDATE + 3 FROM DUAL;

SELECT 1000 * 200 FROM DUAL;

-- 부서 테이블에서 부서이름(dname)과 부서번호(deptno)를 출력하여라.
SELECT * FROM TAB;
SELECT * FROM DEPARTMENT;
SELECT DNAME, DEPTNO FROM DEPARTMENT;