UPDATE TBL_MEMBER SET
    PW = ?, 
    NAME = ?, 
    SI = ?, 
    SGG = ?, 
    EMD = ?, 
    ROADADDR = ?, 
    ADDRDETAIL = ?, 
    ZIPNO = ?, 
    ROADFULLADDR = ?, 
    JIBUNADDR = ?, 
    EMAIL = ?
WHERE ID = ?;

SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_MEMBER' ORDER BY COLUMN_ID;

SELECT 'sb.append("' || COLUMN_NAME || ' = ?, \r\n");' FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_MEMBER' ORDER BY COLUMN_ID;

SELECT 'pstmt.setString(idx++, member.get' || INITCAP(COLUMN_NAME) || '());' FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_MEMBER' ORDER BY COLUMN_ID;

SELECT * FROM TBL_MEMBER;

-- member remove
UPDATE TBL_BOARD SET
WRITER = NULL
WHERE WRITER = 'babamba';

-- 프로시저 선언
-- 회원 탈퇴기능 수행
-- 프로시저이름 : QUIT_PROC
-- 매개변수 P_ID / MEMBER.ID 타입

CREATE OR REPLACE PROCEDURE QUIT_PROC (P_ID TBL_MEMBER.ID%TYPE) IS
BEGIN
    UPDATE TBL_BOARD SET
    WRITER = NULL
    WHERE WRITER = P_ID;

    UPDATE TBL_REPLY SET
    WRITER = NULL
    WHERE WRITER = P_ID;
    
    DELETE TBL_MEMBER
    WHERE ID = P_ID;
    
    COMMIT;
END;
/

SELECT * FROM TBL_MEMBER;

SELECT * FROM TBL_BOARD WHERE WRITER IS NULL ORDER BY 1;

EXECUTE QUIT_PROC('hong');

DELETE FROM TBL_MEMBER WHERE ID = 'tamsasoo';
SAVEPOINT S1;
DELETE FROM TBL_MEMBER WHERE ID = 'javaman2';
SAVEPOINT S2;
ROLLBACK TO S1;