SELECT * FROM TBL_BOARD ORDER BY BNO DESC;

SELECT /*+ INDEX_DESC()*/ * FROM TBL_BOARD;
SELECT /*+ INDEX_DESC()*/ * FROM TBL_BOARD;
SELECT /*+ INDEX_DESC(TBL_BOARD BOARD_PK)*/ * FROM TBL_BOARD;

SELECT RN, BNO, TITLE, CONTENT FROM (
    SELECT
    /*+ INDEX_DESC(TBL_BOARD BOARD_PK) */
    ROWNUM RN, BNO, TITLE, CONTENT
    FROM TBL_BOARD
    WHERE ROWNUM <= 30
)
WHERE RN > 20;

-- 현재 : 페이지 번호가 존재하는 질의문, BNO 역순
-- 댓글 페이징 : 페이지번호가 존재하지 않는 질의문 BNO 정순

    SELECT
    ROWNUM RN, BNO, TITLE, CONTENT
    FROM TBL_BOARD
    WHERE ROWNUM <= 10
    AND BNO > 68;

SELECT
/*+ INDEX_DESC(TBL_BOARD BOARD_PK) */ T.*, ROWNUM
FROM TBL_BOARD T ORDER BY BNO DESC;

SELECT ROWNUM, BNO, TITLE FROM TBL_BOARD ORDER BY BNO;
SELECT /*+ INDEX(TBL_BOARD BOARD_PK) */ ROWNUM, BNO, TITLE FROM TBL_BOARD ORDER BY BNO;

INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER)
SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_BOARD;