CREATE TABLESPACE JSP
    DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\jsp.dbf' SIZE 100M
    AUTOEXTEND ON NEXT 10M ;
    
CREATE USER JSP IDENTIFIED BY 1234 DEFAULT TABLESPACE JSP;

GRANT CONNECT, RESOURCE TO JSP;