CREATE TABLE TBL_REPLY (
    RNO NUMBER(10, 0)CONSTRAINT REPLY_PK PRIMARY KEY,
    BNO NUMBER(10, 0) CONSTRAINT REPLY_BOARD_FK REFERENCES TBL_BOARD(BNO),
    REPLY VARCHAR2(1000) NOT NULL,
    REPLYER VARCHAR2(50) NOT NULL,
    REPLYDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_REPLY;

DROP TABLE TBL_TEST;
CREATE TABLE TBL_TEST (
    REPLYER VARCHAR2(50) NOT NULL,
    REPLYDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY(REPLYER, REPLYDATE)
);

SELECT BNO FROM TBL_BOARD WHERE ROWNUM <= 5 ORDER BY BNO DESC; -- 376927

-- ºñµ¿±â
-- SELECT * FROM TBL_REPLY;
SELECT /*+ INDEX(TBL_REPLY REPLY_PK) */ *
FROM TBL_REPLY
WHERE BNO = 376927
AND RNO > 18
AND ROWNUM <= 10;