DROP TABLE TBL_BOARD;
CREATE TABLE TBL_BOARD (
    BNO NUMBER,
    TITLE VARCHAR2(300),
    CONTENT CLOB,
    HITCOUNT NUMBER DEFAULT 0,
    REGDATE DATE DEFAULT SYSDATE,
    WRITER VARCHAR2(100),
    CATEGORY NUMBER DEFAULT 1
);

DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER (
    ID VARCHAR2(100),
    PW VARCHAR2(100),
    NAME VARCHAR2(100),
    SI VARCHAR2(100),
    SGG VARCHAR2(100),
    EMD VARCHAR2(100),
    ROADADDR VARCHAR2(500),
    ADDRDETAIL VARCHAR2(20),
    ZIPNO VARCHAR2(10),
    ROADFULLADDR VARCHAR2(500),
    JIBUNADDR VARCHAR2(500),
    EMAIL VARCHAR2(200),
    AUTH CHAR DEFAULT 1,
    AUTH_TOKEN VARCHAR2(100)
);

DROP TABLE TBL_REPLY;
CREATE TABLE TBL_REPLY (
    RNO NUMBER,
    CONTENT VARCHAR2(4000),
    REGDATE DATE DEFAULT SYSDATE,
    BNO NUMBER,
    WRITER VARCHAR(100)
);

DROP TABLE TBL_ATTACH;
CREATE TABLE TBL_ATTACH (
    UUID VARCHAR2(50),
    ORIGIN VARCHAR2(500),
    PATH CHAR(10),
    IMAGE CHAR DEFAULT '0',
    ORD NUMBER DEFAULT 1,
    BNO NUMBER
);