CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD (
    BNO NUMBER(10, 0) CONSTRAINT BOARD_PK PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    WRITER VARCHAR(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_BOARD(BNO, TITLE, CONTENT, WRITER)
VALUES(SEQ_BOARD.NEXTVAL, '테스트 제목', '테스트 내용', 'user00');

COMMIT;

SELECT * FROM TBL_BOARD;

SELECT * FROM TBL_BOARD WHERE BNO > 0;